-- cisco-pix
-- plugin_id: 1514

-- DELETE FROM plugin WHERE id = "1514";
-- DELETE FROM plugin_sid where plugin_id = "1514";

-- Cisco PIX Firewall System Log Messages, Version 6.3

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1514, 1, 'cisco-pix', 'Cisco PIX Firewall');

INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 101001, "(Primary) Failover cable OK.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 101002, "(Primary) Bad failover cable. ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 101003, "(Primary) Failover cable not connected (this unit).");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 101004, "(Primary) Failover cable not connected (other unit).");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 101005, "(Primary) Error reading failover cable status.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 102001, "(Primary) Power failure/System reload other side.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 103001, "(Primary) No response from other firewall (reason ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 103002, "(Primary) Other firewall network interface ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 103003, "(Primary) Other firewall network interface ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 103004, "(Primary) Other firewall reports this firewall failed.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 103005, "(Primary) Other firewall reporting failure.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 104001, "(Primary) Switching to ACTIVE (cause: string). ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 104002, "(Primary) Switching to STNDBY (cause: string).");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 104003, "(Primary) Switching to FAILED.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 104004, "(Primary) Switching to OK.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105001, "(Primary) Disabling failover.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105002, "(Primary) Enabling failover.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105003, "(Primary) Monitoring on interface interface_name");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105004, "(Primary) Monitoring on interface interface_name normal");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105005, "(Primary) Lost Failover communications with mate on ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105006, "(Primary) Link status Up on interface interface_name.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105007, "(Primary) Link status Down on interface ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105008, "(Primary) Testing interface interface_name.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105009, "(Primary) Testing on interface interface_name ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105010, "(Primary) Failover message block alloc failed");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105011, "(Primary) Failover cable communication failure");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105020, "(Primary) Incomplete/slow config replication");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105031, "Failover LAN interface is up");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105032, "LAN Failover interface is down");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105034, "Receive a LAN_FAILOVER_UP message from peer.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105035, "Receive a LAN failover interface down msg from peer.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105036, "PIX dropped a LAN Failover command message.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 105037, "The primary and standby units are switching back and ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106001, "Inbound TCP connection denied from IP_address/port to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106002, "protocol Connection denied by outbound list acl_ID src ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106006, "Deny inbound UDP from outside_address/outside_port to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106007, "Deny inbound UDP from outside_address/outside_port to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106010, "Deny inbound protocol src ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106011, "Deny inbound (No xlate) string");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106012, "Deny IP from IP_address to IP_address, IP options hex.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106013, "Dropping echo request from IP_address to PAT address ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106014, "Deny inbound icmp src interface_name: IP_address dst ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106015, "Deny TCP (no connection) from IP_address/port to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106016, "Deny IP spoof from (IP_address) to IP_address on ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106017, "Deny IP due to Land Attack from IP_address to IP_address");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106018, "ICMP packet type ICMP_type denied by outbound list ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106020, "Deny IP teardrop fragment (size = number, offset = ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106021, "Deny protocol reverse path check from source_address to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106022, "Deny protocol connection spoof from source_address to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106023, "Deny protocol src ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106028, "Dropping invalid echo {request|reply} from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106100, "access-list acl_ID {permitted | denied | est-allowed} ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 106101, "The number of ACL log deny-flows has reached limit ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 107001, "RIP auth failed from IP_address: version=number, ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 107002, "RIP pkt failed from IP_address: version=number on ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 108002, "SMTP replaced string: out source_address in ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109001, "Auth start for user user from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109002, "Auth from inside_address/inside_port to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109003, "Auth from inside_address to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109005, "Authentication succeeded for user user from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109006, "Authentication failed for user user from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109007, "Authorization permitted for user user from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109008, "Authorization denied for user user from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109010, "Auth from inside_address/inside_port to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109011, "Authen Session Start: user user, sid number");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109012, "Authen Session End: user user, sid number, elapsed ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109013, "User must authenticate before using this service");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109014, "uauth_lookup_net fail for uauth_in()");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109016, "Cant find authorization ACL acl_ID on PIX for user ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109017, "User at IP_address exceeded auth proxy connection limit ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109018, "Downloaded ACL acl_ID is empty");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109019, "Downloaded ACL acl_ID has parsing error; ACE string");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109020, "Downloaded ACL has config error; ACE");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109021, "Uauth null proxy error");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109022, "exceeded HTTPS proxy process limit");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109023, "User from src_IP_Adress/src_port to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109024, "Authorization denied from source_IP_Address/src_port to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 109025, "Authorization denied (acl=acl_ID) for user user from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 110001, "No route to dest_address from source_address");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 111002, "Begin configuration: IP_address writing to device");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 111003, "IP_address Erase configuration");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 111004, "IP_address end configuration: {FAILED|OK}");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 111005, "IP_address end configuration: OK");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 111007, "Begin configuration: IP_address reading from device.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 111008, "User user executed the command string");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 111009, "User user executed cmd:string");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 112001, "(string:dec) PIX Clear complete.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 199001, "PIX reload command executed from telnet (remote ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 199002, "PIX startup completed. Beginning operation.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 199005, "PIX Startup begin");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 201002, "Too many connections on {static|xlate} global_address! ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 201003, "Embryonic limit exceeded nconns/elimit for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 201005, "FTP data connection failed for IP_address");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 201006, "RCMD backconnection failed for IP_address/port");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 201008, "The PIX is disallowing new connections.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 201009, "TCP connection limit of number for host IP_address on ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 202001, "Out of address translation slots!");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 202005, "Non-embryonic in embryonic list ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 208005, "(function:line_num) pix clear command return code");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 209003, "Fragment database limit of number exceeded: src = ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 209004, "Invalid IP fragment, size = bytes exceeds maximum ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 209005, "Discard IP fragment set with more than number elements: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 210001, "LU SW_Module_Name error = number");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 210002, "LU allocate block (bytes) failed.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 210003, "Unknown LU Object number");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 210005, "LU allocate connection failed");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 210006, "LU look NAT for IP_address failed");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 210007, "LU allocate xlate failed");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 210008, "LU no xlate for inside_address/inside_port ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 210010, "LU make UDP connection for outside_address:outside_port ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 210020, "LU PAT port port reserve failed");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 210021, "LU create static xlate global_address ifc ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 210022, "LU missed number updates");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 211001, "Memory allocation Error");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 211003, "CPU utilization for number seconds = percent");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 212001, "Unable to open SNMP channel (UDP port port) on interface ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 212002, "Unable to open SNMP trap channel (UDP port port) on ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 212003, "Unable to receive an SNMP request on interface ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 212004, "Unable to send an SNMP response to IP Address IP_address ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 212005, "incoming SNMP request (number bytes) on interface ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 213001, "PPTP control daemon socket io string, errno = number.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 213002, "PPTP tunnel hashtable insert failed, peer = IP_address.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 213003, "PPP virtual interface interface_number isnt opened.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 213004, "PPP virtual interface interface_number client ip ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 214001, "Terminating manager session from IP_address on ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 215001, "Bad route_compress() call, sdb= number");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 302003, "Built H245 connection for foreign_address ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 302004, "Pre-allocate H323 UDP backconnection for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 302009, "Rebuilt TCP connection number for foreign_address ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 302010, "connections in use, connections most used");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 302013, "Built {inbound|outbound} TCP connection number for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 302014, "Teardown TCP connection number for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 302015, "Built {inbound|outbound} UDP connection number for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 302016, "Teardown UDP connection number for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 302017, "Built {inbound|outbound} GRE connection id from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 302018, "Teardown GRE connection id from");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 302019, "H.323 library_name ASN Library failed to initialize, ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 302302, "ACL = deny; no sa created");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 303002, "source_address {Stored|Retrieved} dest_address: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 304001, "user source_address Accessed {JAVA URL|URL} ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 304002, "Access denied URL url SRC IP_address DEST IP_address: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 304003, "URL Server IP_address timed out URL url");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 304004, "URL Server IP_address request failed URL url");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 304005, "URL Server IP_address request pending URL url");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 304006, "URL Server IP_address not responding");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 304007, "URL Server IP_address not responding, ENTERING ALLOW ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 304008, "LEAVING ALLOW mode, URL Server is up.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 304009, "Ran out of buffer blocks specified by url-block command");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 305005, "No translation group found for protocol src ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 305006, "{outbound static|identity|portmap|regular) translation ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 305007, "addrpool_free(): Orphan IP IP_address on interface ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 305008, "Free unallocated global IP address.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 305009, "Teardown type) translation from interface):address) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 305010, "Teardown {dynamic|static} translation from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 305011, "Built {dynamic|static} {TCP|UDP|ICMP} translation from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 305012, "Teardown {dynamic|static} {TCP|UDP|ICMP} translation ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 308001, "PIX console enable password incorrect for number tries ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 308002, "static global_address inside_address netmask netmask ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 309002, "Permitted manager connection from IP_address.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 311001, "LU loading standby start");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 311002, "LU loading standby end");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 311003, "LU recv thread up");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 311004, "LU xmit thread up");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 312001, "RIP hdr failed from IP_address: cmd=string, ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 313001, "Denied ICMP type=number, code=code from IP_address on ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 313003, "Invalid destination for ICMP error");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 314001, "Pre-allocate RTSP UDP backconnection for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 315004, "Fail to establish SSH session because PIX RSA host key ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 315011, "SSH session from IP_address on interface interface_name ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 316001, "Denied new tunnel to IP_address. VPN peer limit ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 317001, "No memory available for limit_slow");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 317002, "Bad path index of number for IP_address, number max");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 317003, "IP routing table creation failure - reason");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 317004, "IP routing table limit warning");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 317005, "IP routing table limit exceeded - reason, IP_address ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 318001, "Internal error: reason");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 318002, "Flagged as being an ABR without a backbone area");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 318003, "Reached unknown state in neighbor state machine");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 318004, "area string lsid IP_address mask netmask adv IP_address ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 318005, "lsid IP_address adv IP_address type number gateway ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 318006, "if interface_name if_state number");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 318007, "OSPF is enabled on interface_name during idb ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 318008, "OSPF process number is changing router-id. Reconfigure ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 320001, "The subject name of the peer cert is not allowed for ");
-- INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 4000nn, "IDS:number string from IP_address to IP_address on ");
-- INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 4000nn, "and have the following format:");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 400013, "IDS:2003 ICMP redirect from 10.4.1.2 to 10.2.1.1 on interface dmz");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 400032, "UDP Snork attack from 10.1.1.1 to 192.168.1.1 on interface outside");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 401001, "Shuns cleared");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 401002, "Shun added: IP_address IP_address port port");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 401003, "Shun deleted: IP_address");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 401004, "Shunned packet: IP_address ==) IP_address on interface ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 401005, "can be used to evaluate further risk assessment concerning this ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 401005, "Shun add failed: unable to allocate resources for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 402101, "decaps: recd IPSEC packet has invalid spi for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 402102, "decapsulate: packet missing {AH|ESP}, ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 402103, "identity doesnt match negotiated identity (ip) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 402106, "Recd packet not an IPSEC packet (ip) dest_address= ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403101, "PPTP session state not established, but received an XGRE ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403102, "PPP virtual interface interface_name rcvd pkt with ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403103, "PPP virtual interface max connections reached.");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403104, "PPP virtual interface interface_name requires mschap ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403106, "PPP virtual interface interface_name requires RADIUS ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403107, "PPP virtual interface interface_name missing aaa server ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403108, "PPP virtual interface interface_name missing client ip ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403109, "Recd packet not an PPTP packet. (ip) dest_address= ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403110, "PPP virtual interface interface_name, user: user ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403500, "PPPoE - Service name any not received in PADO. ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403501, "PPPoE - Bad host-unique in PADO - packet dropped. ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403502, "PPPoE - Bad host-unique in PADS - dropping packet. ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403503, "PPPoE:PPP link down:reason ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403504, "PPPoE:No vpdn group for PPPoE is created");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403505, "PPPoE:PPP - Unable to set default route to IP_address ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 403506, "PPPoE:failed to assign PPP IP_address netmask netmask ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 404101, "ISAKMP: Failed to allocate address for client from pool ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 405001, "Received ARP {request | response} collision from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 405002, "Received mac mismatch collision from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 405101, "Unable to Pre-allocate H225 Call Signalling Connection ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 405102, "Unable to Pre-allocate H245 Connection for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 405103, "H225 message from src_ip/src_port) to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 405104, "H225 message received from outside_address/outside_port ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 406001, "FTP port command low port: IP_address/port to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 406002, "FTP port command different address: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 407001, "Deny traffic for local-host ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 407002, "Embryonic limit neconns/elimit for through connections ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 408001, "IP route counter negative - reason, IP_address Attempt: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409001, "Database scanner: external LSA IP_address netmask is ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409002, "db_free: external LSA IP_address netmask");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409003, "Received invalid packet: reason from IP_address, ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409004, "Received reason from unknown neighbor IP_address");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409005, "Invalid length number in OSPF packet from IP_address ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409006, "Invalid lsa: reason Type number, LSID IP_address from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409007, "Found LSA with the same host bit set but using different ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409008, "Found generating default LSA with non-zero mask LSA ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409009, "OSPF process number cannot start. There must be at least ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409010, "Virtual link information found in non-backbone area: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409011, "OSPF detected duplicate router-id IP_address from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409012, "Detected router with duplicate router ID IP_address in ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409013, "Detected router with duplicate router ID IP_address in ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 409023, "Attempting AAA Fallback method method_name) for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 410001, "UDP DNS packet dropped due to domainname length check ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 410001, "UDP DNS packet dropped due to label length check of 63 ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 410001, "UDP DNS packet dropped due to packet length check of n) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 410001, "UDP DNS packet dropped due to compression length check ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 411001, "Line protocol on interface interface_name changed state ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 411002, "Line protocol on interface interface_name changed state ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 416001, "Dropped UDP SNMP packet from source interface) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 500001, "ActiveX content modified src IP_address dest IP_address ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 500002, "Java content modified src IP_address dest IP_address on ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 500003, "Bad TCP hdr length (hdrlen=bytes, pktlen=bytes) from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 500004, "Invalid transport field for protocol=protocol, from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 501101, "User transitioning priv level");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 502101, "New user added to local dbase: Uname: user Priv: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 502102, "User deleted from local dbase: Uname: user Priv: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 502103, "User priv level changed: Uname: user From: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 503001, "Process number, Nbr IP_address on interface_name from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 602101, "PMTU-D packet number bytes greater than effective mtu ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 602102, "Adjusting IPSec tunnel mtu...");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 602201, "ISAKMP Phase 1 SA created (local ip)/port) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 602301, "sa created... ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 602302, "deleting sa");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 603101, "PPTP received out of seq or duplicate pkt, ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 603102, "PPP virtual interface interface_name - user: user aaa ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 603103, "PPP virtual interface interface_name - user: user aaa ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 603104, "PPTP Tunnel created, tunnel_id is number, ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 603105, "PPTP Tunnel deleted, tunnel_id = number, ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 603106, "L2TP Tunnel created, tunnel_id is number, ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 603107, "L2TP Tunnel deleted, tunnel_id = number, remote_peer_ip ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 603108, "Built PPTP Tunnel at interface_name, tunnel-id = ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 603109, "Teardown PPPOE Tunnel at interface_name, tunnel-id = ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 604101, "DHCP client interface interface_name: Allocated ip = ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 604102, "DHCP client interface interface_name: address released");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 604103, "DHCP daemon interface interface_name: address granted ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 604104, "DHCP daemon interface interface_name: address released");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 605004, "Login denied from {source_address/source_port | serial} ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 605005, "Login permitted from {source_address/source_port | ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 606001, "PDM session number number from IP_address started");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 606002, "PDM session number number from IP_address ended");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 607001, "Pre-allocate SIP connection_type secondary channel for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 608001, "Pre-allocate Skinny connection_type secondary channel ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 609001, "Built local-host interface_name:IP_address");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 609002, "Teardown local-host interface_name:IP_address duration ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 610001, "NTP daemon interface interface_name: Packet denied from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 610002, "NTP daemon interface interface_name: Authentication ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 610101, "Authorization failed: Cmd: command Cmdtype: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611101, "User authentication succeeded: Uname: user");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611102, "User authentication failed: Uname: user");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611103, "User logged out: Uname: user");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611104, "Serial console idle timeout exceeded");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611301, "VPNClient: NAT configured for Client Mode with no split ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611302, "VPNClient: NAT exemption configured for Network ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611303, "VPNClient: NAT configured for Client Mode with split ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611304, "VPNClient: NAT exemption configured for Network ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611305, "VPNClient: DHCP Policy installed: Primary DNS: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611306, "VPNClient: Perfect Forward Secrecy Policy installed");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611307, "VPNClient: Head end : IP_address");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611308, "VPNClient: Split DNS Policy installed: List of domains: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611309, "VPNClient: Disconnecting from head end and uninstalling ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611310, "VNPClient: XAUTH Succeeded: Peer: IP_address");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611311, "VNPClient: XAUTH Failed: Peer: IP_address");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611312, "VPNClient: Backup Server List: reason");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611313, "VPNClient: Backup Server List Error: reason");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611314, "VPNClient: Load Balancing Cluster with Virtual IP: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611315, "VPNClient: Disconnecting from Load Balancing Cluster ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611316, "VPNClient: Secure Unit Authentication Enabled");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611317, "VPNClient: Secure Unit Authentication Disabled");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611318, "VPNClient: User Authentication Enabled: Auth Server IP: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611319, "VPNClient: User Authentication Disabled");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611320, "VPNClient: Device Pass Thru Enabled");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611321, "VPNClient: Device Pass Thru Disabled");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611322, "VPNClient: Extended XAUTH conversation initiated when ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 611323, "VPNClient: Duplicate split nw entry");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 612001, "Auto Update succeeded:filename, version:number");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 612002, "Auto Update failed:filename, version:number, ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 612003, "Auto Update failed to contact:url, reason:reason ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 613001, "Checksum Failure in database in area string Link State ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 613002, "interface interface_name has zero bandwidth");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 613003, "IP_address netmask changed from area string to area ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 614001, "Split DNS: request patched from server: IP_address to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 614002, "Split DNS: reply from server:IP_address reverse patched ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 620001, "Pre-allocate CTIQBE {RTP | RTCP} secondary channel for ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 620002, "Unsupported CTIQBE version: hex: from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 701001, "alloc_user() out of Tcp_user objects");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702201, "ISAKMP Phase 1 delete received (local ip) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702202, "ISAKMP Phase 1 delete sent (local ip) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702203, "ISAKMP DPD timed out (local ip) (initiator|responder), ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702204, "ISAKMP Phase 1 retransmission (local ip) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702205, "ISAKMP Phase 2 retransmission (local ip) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702206, "ISAKMP malformed payload received (local ip) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702207, "ISAKMP duplicate packet detected (local ip) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702208, "ISAKMP Phase 1 exchange started (local ip) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702209, "ISAKMP Phase 2 exchange started (local ip) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702210, "ISAKMP Phase 1 exchange completed(local ip) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702211, "ISAKMP Phase 2 exchange completed(local ip) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702212, "ISAKMP Phase 1 initiating rekey (local ip) ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702301, "lifetime expiring... ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702302, "replay rollover detected...");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 702303, "sa_request...");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 703001, "H.225 message received from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 703002, "Received H.225 Release Complete with ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 709001, "FO replication failed: cmd=command returned=code");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 709002, "FO unreplicable: cmd=command");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 709003, "(Primary) Beginning configuration replication: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 709004, "(Primary) End Configuration Replication (ACT)");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 709005, "(Primary) Beginning configuration replication: ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 709006, "(Primary) End Configuration Replication (STB)");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 709007, "Configuration replication failed for command command");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 710001, "TCP access requested from source_address/source_port to ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 710002, "{TCP|UDP} access permitted from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 710003, "{TCP|UDP} access denied by ACL from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 710004, "TCP connection limit exceeded from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 710005, "{TCP|UDP} request discarded from ");
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1514, 710006, "protocol request discarded from source_address to ");
