INSERT IGNORE INTO plugin (id, type, name, description) VALUES (4008, 1, 'McAfee-Epo', 'McAfee-Epo');
-- plugin_id: 4008
--
-- Plugin sids from McAfee ePO

DELETE FROM plugin WHERE id = "4008";
DELETE FROM plugin_sid where plugin_id = "4008";


INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1000 , "NetShield service");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1001 , "NetShield service ended successfully.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1002 , "Task started successfully.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1003 , "Error starting Task.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1004 , "Task has completed successfully.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1005 , "Error while stopping task.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1024 , "Infected file found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1025 , "Infected file successfully Cleaned.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1026 , "Unable to clean infected file.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1027 , "Infected file deleted.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1028 , "Unable to delete infected file.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1029 , "File to be excluded from scans.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1030 , "Unable to exclude item from scans.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1031 , "Infected file access denied.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1032 , "Infected file was moved to quarantine area.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1033 , "Unable to move infected file to quarantine.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1034 , "Scan completed. No viruses found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1035 , "Scan was cancelled.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1036 , "Memory infected.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1037 , "Infected boot record found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1038 , "Scan found infected files.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1039 , "Scan found and cleaned infected files.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1040 , "Activity Log error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1041 , "Scan reports memory allocation error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1042 , "Path too long.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1043 , "Media is write protected.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1044 , "Specified media not found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1045 , "Specified scan item is invalid.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1046 , "File I/O errors.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1047 , "Disk I/O errors.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1048 , "Scan reports general system error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1049 , "Scan reported an internal application error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1050 , "Unable to repair password protected");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1051 , "Unable to scan password protected");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1052 , "Infected Binder Object");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1053 , "Infected file found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1054 , "Infected file deleted.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1055 , "Unable to delete infected file.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1056 , "File moved to quarantine.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1057 , "Unable to move infected file to quarantine.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1059 , "Scan Timed Out");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1060 , "Boot sector virus was cleaned");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1061 , "Error while cleaning boot sector virus");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1062 , "Error sending alert");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1063 , "Invalid options specified");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1064 , "Service was started.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1065 , "Service ended.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1066 , "Task started ok");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1067 , "Unable to start scheduled task.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1068 , "Scheduled task was stopped.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1069 , "Error stopping scheduled task.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1070 , "Task was successful.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1071 , "Task was canceled.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1076 , "Error logging information.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1077 , "Memory allocation error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1086 , "Scan Process Error");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1087 , "On-access Scan started");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1088 , "On-access scan stopped.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1089 , "Scan Settings.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1090 , "OAS stopped");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1091 , "JavaScript security violation detected and blocked");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1092 , "Access Protection rule violation detected and blocked");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1093 , "Buffer Overflow detected and blocked");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1094 , "Port blocking rule violation detected");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1095 , "Access Protection rule violation detected and NOT blocked");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1096 , "Port blocking rule violation detected and NOT blocked");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1099 , "Buffer Overflow detected and NOT blocked");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1100 , "Macro Detected in file");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1101 , "Macro Deleted from file");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1102 , "Multiple extension heuristic detection - moved");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1103 , "Prescan needed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1104 , "Multiple extension heuristic detection - delete on reboot");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1106 , "Multiple extension heuristic detection - message deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1118 , "The update was successful");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1119 , "The update failed; see event log");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1120 , "The update is running");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1121 , "The update was cancelled");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1122 , "The upgrade is running");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1123 , "The upgrade failed; see event log");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1124 , "The upgrade was cancelled");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1125 , "The DAT version was not new enough");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1126 , "Scan was cancelled by autoupdate of DAT files");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1127 , "OAS Scanning Engine Disabled");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1128 , "Scan time exceeded");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1129 , "Scan shut down by Windows");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1200 , "Process started");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1201 , "Process Ended");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1202 , "On-demand scan started");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1203 , "On Demand scan complete");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1204 , "Report OS & Serial");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1270 , "file infected.  No cleaner available - quarantined successfully");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1271 , "file infected.  No cleaner available - heuristic detection");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1272 , "file infected.  Undetermined clean error - quarantined successfully");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1273 , "file infected.  Clean error");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1274 , "file infected.  No cleaner available - quarantine failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1275 , "file infected.  No cleaner available - heuristic detection");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1276 , "file infected.  Undetermined clean error - quarantine failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1277 , "file infected.  Clean error");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1278 , "file infected.  No cleaner available - file deleted successfully");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1279 , "file infected.  No cleaner available - heuristic detection - deleted successfully");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1280 , "file infected.  Undetermined clean error - deleted successfully");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1281 , "file infected.  Clean error");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1282 , "file infected.  No cleaner available - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1283 , "file infected.  Clean error - heuristic detection");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1284 , "file infected.  Undetermined clean error - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1285 , "file infected.  Clean error - Encrypted file - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1286 , "file infected.  No cleaner available - continued scanning (ODS)");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1287 , "file infected.  Clean error - heuristic detection - continued scanning (ODS)");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1288 , "file infected.  Undetermined clean error - continued scanning (ODS)");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1289 , "file infected.  Clean error - Encrypted file - continued scanning (ODS)");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1290 , "file infected.  No cleaner available - OAS denied access and continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1291 , "file infected.  Clean error - heuristic detection - OAS denied access and continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1292 , "file infected.  Undetermined clean error - OAS denied access and continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1293 , "file infected.  Quarantine failed - deleted successfully");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1294 , "file infected.  Quarantine failed - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1295 , "file infected.  Move failed - continued scanning (ODS)");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1296 , "file infected.  Move failed - denied access and continued (OAS)");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1297 , "file infected.  Delete failed - quarantined");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1298 , "file infected.  Delete failed - quarantine failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1299 , "file infected.  Delete failed - continued scanning (ODS)");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1300 , "file infected.  Delete failed - denied access and continued (OAS)");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1301 , "Multiple extension heuristic detection - clean error - quarantined successfully");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1302 , "Multiple extension heuristic detection - move failed - clean error");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1303 , "Multiple extension heuristic detection - clean error - deleted successfully");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1304 , "Multiple extension heuristic detection - clean error - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1305 , "Multiple extension heuristic detection - clean error - denied access and continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1306 , "Multiple extension heuristic detection - move failed - deleted successfully");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1307 , "Multiple extension heuristic detection - move failed - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1308 , "Multiple extension heuristic detection - move failed - denied access and continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1309 , "Multiple extension heuristic detection - delete failed - quarantined successfully");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1310 , "Multiple extension heuristic detection - delete failed - quarantine failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1311 , "Multiple extension heuristic detection - delete failed - denied access and continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1312 , "Move failed - delete failed - file will be deleted on reboot");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1313 , "Multiple extension heuristic detection - move failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1314 , "Encrypted file - clean error - delete on reboot");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1315 , "Heuristic detection - clean error - delete on reboot");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1316 , "Multiple extension heuristic detection - clean error - delete on reboot");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1317 , "No cleaner available - clean error - delete on reboot");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1318 , "Undetermined - clean error - delete on reboot");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1319 , "Undetermined - clean error - message deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1320 , "Encrypted - clean error - message deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1321 , "Heuristic detection - clean error - message deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1322 , "Multiple extension heuristic detection - clean error - message deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1323 , "Clean error - message deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1324 , "Move failed - message deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1325 , "Multiple extension heuristic detection - move failed - message deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1329 , "Offline Virtual Image Scan Failed due to a sharing violation");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1330 , "Offline Virtual Image Scan Failed due to a removable drive conflict");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1331 , "Offline Virtual Image Scan Failed unable to virtualize registry");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1332 , "Offline Virtual Image Scan Failed because image is suspended or running");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1333 , "Offline Virtual Image Scan Copied DATs successfuuly");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1334 , "Offline Virtual Image Scan Copy DATs Failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1335 , "Offline Virtual Image scan started");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1336 , "Offline Virtual Image scan completed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1337 , "Offline Virtual Image scan failed due to a partition mount failure");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1338 , "Offline Virtual Image scan failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1339 , "Offline Virtual Image scan failed unable to load required library");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1500 , "Infected email cleaned");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1501 , "Infected email quarantined");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1502 , "Unable to clean infected mail");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1503 , "Infected email detected");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1504 , "Infected mail item deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1505 , "Email content filtered");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1506 , "Email content blocked");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1507 , "Inbound email suspend for low disk");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1508 , "Inbound Mail Resumed.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1509 , "Startup request successfully processed.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1510 , "Shutdown request successfully processed.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1511 , "Warning - abnormal termination!");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1512 , "A maximum load condition is occurring!");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1513 , "Mail virus quarantined and cleaned");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1514 , "Mail virus quarantined (not cleaned)");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1700 , "GroupShield Exchange - service started successfully.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1701 , "GroupShield Exchange -  service ended successfully.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1702 , "GroupShield Exchange - File copy has been blocked");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1703 , "GroupShield Exchange - Message is infected");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1704 , "GroupShield Exchange - Message blocked");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1705 , "GroupShield Exchange - Infected file found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1706 , "GroupShield Exchange - Infected file successfully cleaned.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1707 , "GroupShield Exchange - Infected file was moved to quarantine area.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1708 , "GroupShield Exchange - Scheduled Once Scan Started");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1709 , "GroupShield Exchange - Scheduled Repeat Event Scan Started");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1710 , "GroupShield Exchange - Scheduled Scan Finished");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1711 , "GroupShield Exchange - Scheduled Scan Failed To Start");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1712 , "GroupShield Exchange - Internal Error occurred");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1713 , "GroupShield Exchange - On-Demand Scan Started");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1714 , "GroupShield Exchange - On-Demand Scan Finished");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1715 , "GroupShield Exchange - AV Engine has been stopped");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1716 , "GroupShield Exchange - AV Engine has been started");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1717 , "GroupShield Exchange - An update Failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1718 , "GroupShield Exchange - An update has started");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1719 , "GroupShield Exchange - No update is available");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1720 , "GroupShield Exchange - An update was successful");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1721 , "GroupShield Exchange - Disk space is low");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1722 , "GroupShield Exchange - Infected file");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1725 , "GroupShield Exchange - Nearly end of designed life");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1726 , "GroupShield Exchange - End of designed life reached");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1800 , "GroupShield Domino: Task started successfully.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1801 , "GroupShield Domino: Error starting task.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1802 , "GroupShield Domino: Task has completed.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1803 , "GroupShield Domino: Error while stopping task.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1804 , "GroupShield Domino: File virus found and cleaned.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1805 , "GroupShield Domino: Infected file successfully quarantined.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1806 , "GroupShield Domino: Infected file deleted.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1807 , "GroupShield Domino Infected file ignored.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1808 , "GroupShield Domino Quarantined a LotusScript Exception");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1809 , "GroupShield Domino LotusScript Exception found and ignored.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1810 , "GroupShield Domino Quarantined a Formula Exception");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1811 , "GroupShield Domino Formula Exception found and ignored.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1812 , "GroupShield Domino Quarantined a Content Exception");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1813 , "GroupShield Domino Content Exception found and ignored.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1814 , "GroupShield Domino Unable to read configuration database.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1815 , "GroupShield Domino Unable to write to configuration database.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1816 , "GroupShield Domino AutoGO   update unable to restart task");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1817 , "GroupShield Domino AutoGO   update failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1818 , "GroupShield for Lotus Domino: Attachments Blocked");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 1900 , "New MIB File Available");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2000 , "Infected file found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2001 , "Infected file successfully cleaned.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2002 , "Unable to clean infected file.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2003 , "Infected file deleted.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2004 , "Unable to delete infected file.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2005 , "File to be excluded from scans.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2006 , "Unable to exclude item from scans.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2007 , "Infected file access denied.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2008 , "Infected file was moved to quarantine area.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2009 , "Unable to move infected file to quarantine.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2010 , "Centralized Alerting - Infected file found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2011 , "Centralized Alerting - Infected file successfully cleaned.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2012 , "Centralized Alerting - Unable to clean infected file.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2013 , "Centralized Alerting - Infected file deleted.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2014 , "Centralized Alerting - Unable to delete infected file.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2015 , "Centralized Alerting - File to be excluded from scans.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2016 , "Centralized Alerting - Unable to exclude item from scans.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2017 , "Centralized Alerting -");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2018 , "Centralized Alerting - Infected file was moved to quarantine area.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2019 , "Centralized Alerting - Unable to move infected file to quarantine.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2020 , "Boot record infection found");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2021 , "Boot record infection cleaned");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2022 , "Boot record infection clean error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2023 , "New File Virus Found");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2024 , "New File Virus Found And Deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2025 , "New File Virus Found But Move Failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2026 , "New File Virus Found And Moved");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2027 , "New File Virus Found But Move Failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2028 , "MBR Virus Found");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2100 , "Outbreak Rule Name.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2201 , "McAfee Agent: Failed to install software package");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2202 , "McAfee Agent: Install retry limit reached for software package");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2204 , "McAfee Agent: Insufficient disk space to install software");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2208 , "McAfee Agent: Insufficient disk space to download software");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2216 , "McAfee Agent: Cannot install software due to OS version mismatch");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2264 , "McAfee Agent: Property Collection Failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2328 , "McAfee Agent: Enforce Task Failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2401 , "Update Successful");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2402 , "Update Failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2411 , "Deployment Successful");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2412 , "Deployment Failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 2413 , "Attempt to uninstall McAfee Agent");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3000 , "Scan task completed. No viruses found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3001 , "Task was cancelled.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3002 , "Virus found in Memory.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3003 , "Infected boot record found");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3004 , "Task found infected files.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3005 , "Task found and cleaned infected files.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3006 , "Task error while accessing activity log file.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3007 , "Task reports memory allocation error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3008 , "Directory length access error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3009 , "Media is write protected.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3010 , "Specified media not found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3011 , "Specified scan item is invalid.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3012 , "File I/O errors.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3013 , "Disk I/O errors.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3014 , "Task reports general system error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3015 , "Task reported an internal application error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3016 , "Error opening Service Manager.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3017 , "Error starting drivers.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3018 , "Error occurred starting log subsystem.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3019 , "Error obtaining device driver versions.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3020 , "Invalid virus signature files.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3021 , "Scan engine error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3022 , "Initialization error with scan buffer.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3023 , "Memory allocation error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3024 , "Unknown error reported.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3025 , "Error sending new options to device driver.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3026 , "Error sending exclude information to the driver.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3027 , "Error sending move to folder to the driver.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3028 , "Error obtaining log data from device driver.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3029 , "Error occurred while enabling driver.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3030 , "Error occurred while disabling driver.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3031 , "Error while obtaining statistical data from driver.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3032 , "Error while trying to open/create activity log file.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3033 , "Activity log file maximum size reached.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3034 , "Unable to write the activity log file.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3035 , "Error launching a program upon virus infection.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3036 , "Error during initialization of the activity log file.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3037 , "Memory grant unavailable.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3038 , "Error writing to log");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3039 , "Centralized Alerting - Scan completed. No viruses found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3040 , "Centralized Alerting - Scan was cancelled.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3041 , "Centralized Alerting - Virus found in Memory.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3042 , "Centralized Alerting - Infected boot record found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3043 , "Centralized Alerting - Scan found infected files.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3044 , "Centralized Alerting - Scan found and cleaned infected files.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3045 , "Centralized Alerting - Error while accessing activity log file.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3046 , "Centralized Alerting - Scan reports memory allocation error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3047 , "Centralized Alerting - Directory length access error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3048 , "Centralized Alerting - Media is write protected.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3049 , "Centralized Alerting - Specified media not found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3050 , "Centralized Alerting - Specified scan item is invalid.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3051 , "Centralized Alerting - File I/O errors.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3052 , "Centralized Alerting - Disk I/O errors.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3053 , "Centralized Alerting - Scan reports general system error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3054 , "Centralized Alerting - Scan reported an internal application error.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 3055 , "Error stopping drivers");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 4650 , "Detected Spam Email");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 4651 , "Spam Email Scanning Statistics");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 4700 , "Failed to connect to CMA updater");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 4701 , "Failed to connect to CMA scheduler");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 4702 , "Failed to save schedule data into CMA");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 8000 , "Infected item found");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 8500 , "Banned item found");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 8501 , "Encrypted/Corrupted item found");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 8502 , "Item matched filtering criteria");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 8503 , "Item matched spam criteria");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 11001 , "Application blocked");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 12000 , "Rogue System Sensor started successfully");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 12001 , "Rogue System Sensor failed to start");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 12002 , "Rogue System Sensor stopped");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 13001 , "The system is compliant or non-compliant with rules");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 13002 , "System Compliance Profiler rule violation");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16000 , "Computers are non-compliant");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16001 , "Reserved for future use");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16002 , "Master Repository Update succeeded");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16003 , "Master Repository Update failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16004 , "Distributed Repository Replication succeeded");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16005 , "Distributed Repository Replication failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16006 , "New Rogue System detected");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16007 , "Subnet has become unmonitored by Rogue System Sensor");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16008 , "Active Directory Discovery task ran successfully.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16009 , "Active Directory Discovery task failed.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16012 , "Active Directory Discovery task added computers.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16013 , "Active Directory Discovery task removed computers.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16014 , "ePOAuditEvents table is full.  Auto Purge procedure is activated.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16015 , "Auto Purge procedure has completed successfully for epoAuditEvents table.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16016 , "Purge procedure has failed to complete for epoAuditEvents table.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16017 , "Import computers task succeeded.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16018 , "Import computers task added computers.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16019 , "Import computers task removed computers.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16020 , "Import computers task failed.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16021 , "NT Domain sync task succeeded.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16022 , "NT Domain sync task added computers.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16023 , "NT Domain sync task removed computers.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16024 , "NT Domain sync task failed.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16025 , "Agent Handler down");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16026 , "Group added");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16027 , "Error initializing licensing data");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16028 , "License check succeeded");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 16029 , "License check failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 18000 , "Host intrusion detected and handled");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 18001 , "Network intrusion detected and handled");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 18002 , "Application blocked");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 18003 , "Failed Quarantine check");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 18999 , "The IPS Event table is full.  Further events will be ignored until events are archived.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21024 , "Unwanted program found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21025 , "Unwanted program successfully cleaned.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21026 , "Unable to clean unwanted program.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21027 , "Unwanted program deleted.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21028 , "Unable to delete unwanted program.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21031 , "Unwanted program access denied.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21032 , "Unwanted program was moved to quarantine area.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21033 , "Unable to move unwanted program to quarantine.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21036 , "Unwanted program found in memory");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21054 , "Unwanted program deleted.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21055 , "Unable to delete unwanted program.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21056 , "Unwanted program moved to quarantine");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21057 , "Unable to move unwanted program to quarantine.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21270 , "Unwanted program quarantined - no cleaner");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21271 , "Unwanted program quarantined - Heuristics");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21272 , "Unwanted program quarantined - can't clean");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21273 , "Unwanted program quarantined - encrypted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21274 , "Unwanted program not cleaned or quarantined");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21275 , "Unwanted program - heuristics - quarantine failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21276 , "Unwanted program - clean error - quarantine failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21277 , "Unwanted program - encrypted - quarantine failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21278 , "Unwanted program - no cleaner - deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21279 , "Unwanted program - heuristics - no cleaner - deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21280 , "Unwanted program - clean error - deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21281 , "Unwanted program - encrypted - deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21282 , "Unwanted program - no cleaner - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21283 , "Unwanted program - heuristics - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21284 , "unwanted program - clean error - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21285 , "Unwanted program - encrypted - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21286 , "Unwanted program - no cleaner - continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21287 , "Unwanted program - heuristics - continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21288 , "Unwanted program - clean error - continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21289 , "Unwanted program - encrypted - continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21290 , "Unwanted program - no cleaner - denied access");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21291 , "Unwanted program - heuristics - denied access");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21292 , "Unwanted program - clean error - denied access");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21293 , "Unwanted program - quarantine failed - deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21294 , "Unwanted program - quarantine failed - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21295 , "Unwanted program - quarantine failed - continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21296 , "Unwanted program - quarantine failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21297 , "Unwanted program - delete failed - quarantined");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21298 , "Unwanted program - delete failed - quarantine failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21299 , "Unwanted program - delete failed - continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21300 , "Unwanted program - delete failed - denied access");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21400 , "User-specified unwanted program found.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21401 , "User-specified unwanted program - clean error - continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21402 , "User-specified unwanted program - clean error - quarantine failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21403 , "User-specified unwanted program - clean error - quarantined");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21404 , "User-specified unwanted program - clean error - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21405 , "User-specified unwanted program - clean error - deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21406 , "User-specified unwanted program was moved to quarantine area.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21407 , "User-specified unwanted program - quarantine failed - delete failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21408 , "User-specified unwanted program - quarantine failed - deleted");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21409 , "User-specified unwanted program - quarantine failed - continued");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21410 , "User-specified unwanted program deleted.");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21411 , "User-specified unwanted program - delete failed - quarantine failed");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21412 , "User-specified unwanted program - delete failed - quarantined");
INSERT INTO plugin_sid (plugin_id, sid, name) values (4008, 21413 , "User-specified unwanted program - delete failed - continued");
